# ml_05
## 로지스틱 회귀

In [1]:
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [2]:
iris = load_iris()
X_train,X_test,y_train,y_test = train_test_split(iris.data,iris.target,random_state=1)

In [3]:
from sklearn.linear_model import LogisticRegression

model=LogisticRegression() # default value C=1.0
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [5]:
pred_y=model.predict(X_test)
print('Score: %f' % model.score(X_test,y_test))

Score: 0.842105


In [6]:
print(pred_y)
print(y_test)
print('Score: %f (Error: %d)' % (np.mean(pred_y==y_test),np.sum(pred_y!=y_test)) )
print(np.where(pred_y!=y_test))
print(model.predict_proba(X_test[5:6]))

[0 1 1 0 2 2 2 0 0 2 1 0 2 1 2 0 1 2 0 0 2 2 2 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0]
[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 1 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0]
Score: 0.842105 (Error: 6)
(array([ 5, 14, 17, 20, 21, 22], dtype=int32),)
[[ 0.02728121  0.41535346  0.55736533]]


In [4]:
print(model.coef_)
print(model.intercept_)

[[ 0.41079874  1.35827919 -2.13916152 -0.96119148]
 [ 0.66283378 -1.70134773  0.22156197 -0.91724019]
 [-1.72734999 -1.06196409  2.32850534  2.1151445 ]]
[ 0.27132106  0.56418839 -0.85023319]
